import { HighlightedSortOrders, OSISBook, SermonEventType, SermonSortOption } from "../models"

export type SermonsParams = {
    path?: string | null,
    page?: number,
    pageSize?: number,
    book?: OSISBook | null,
    chapter?: number | null,
    chapterEnd?: number | null,
    verse?: number | null,
    verseEnd?: number | null,
    eventType?: SermonEventType | null,
    searchKeyword?: string | null,
    languageCode?: string | null,
    requireAudio?: boolean,
    requireVideo?: boolean,
    series?: string | null,
    broadcasterID?: string | null,
    sermonIDs?: string[] | null,
    speakerName?: string | null,
    year?: number | null,
    sortBy?: SermonSortOption | null,
    highlightedSort?: HighlightedSortOrders | null,
    staffPick?: boolean,
    featured?: boolean,
    listenerRecommended?: boolean,
    updated?: boolean,
    includeDrafts?: boolean,
    includeScheduled?: boolean,
    includePublished?: boolean
}